version: '3.7'
services:
  backend-green:
    image: sivertschou/dundring-backend:${TAG_GREEN}
    container_name: backend-dev-green
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
    networks:
      - caddy
      - dundring-dev
    labels:
      caddy: dev.dundring.com
      caddy.reverse_proxy: '/api* {{upstreams 8080}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

  frontend-green:
    image: sivertschou/dundring-frontend:${TAG_GREEN}
    container_name: frontend-dev-green
    restart: always
    networks:
      - caddy
    labels:
      caddy: dev.dundring.com
      caddy.reverse_proxy: '{{upstreams 80}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

  backend-blue:
    image: sivertschou/dundring-backend:${TAG_BLUE}
    container_name: backend-dev-blue
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
    networks:
      - caddy
      - dundring-dev
    labels:
      caddy: dev.dundring.com
      caddy.reverse_proxy: '/api* {{upstreams 8080}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

  frontend-blue:
    image: sivertschou/dundring-frontend:${TAG_BLUE}
    container_name: frontend-dev-blue
    restart: always
    networks:
      - caddy
    labels:
      caddy: dev.dundring.com
      caddy.reverse_proxy: '{{upstreams 80}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

networks:
  caddy:
    external: true
  dundring-dev:
    external: true
