version: '3.7'
services:
  postgres:
    image: postgres:16.1-alpine
    container_name: dundring-postgres
    environment:
      POSTGRES_DB: dundring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ['5432:5432']
  redis:
    image: redis:7.2-alpine
    container_name: dundring-redis
    ports: ['6379:6379']
