version: '3.7'
services:
  mysql:
    image: mysql:8.2
    container_name: mysql-${TAG}
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: dundring
    ports:
      - '3306:3306'
    networks:
      - dundring

  backend:
    image: sivertschou/dundring-backend:${TAG}
    container_name: backend-${TAG}
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/dundring
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - caddy
      - dundring
    labels:
      caddy: ${TAG}.dundring.com
      caddy.reverse_proxy: '/api* {{upstreams 8080}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

  frontend:
    image: sivertschou/dundring-frontend:${TAG}
    container_name: frontend-${TAG}
    networks:
      - caddy
    labels:
      caddy: ${TAG}.dundring.com
      caddy.reverse_proxy: '{{upstreams 80}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

networks:
  caddy:
    external: true
  dundring:
