version: '3.7'
services:
  postgres:
    image: postgres:15.4
    container_name: postgres-${TAG}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dundring
    ports:
      - '5432:5432'
    networks:
      - dundring

  backend:
    image: sivertschou/dundring-backend:${TAG}
    container_name: backend-${TAG}
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/dundring
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - caddy
      - dundring
    labels:
      caddy: ${TAG}.dundring.com
      caddy.reverse_proxy: '/api* {{upstreams 8080}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

  frontend:
    image: sivertschou/dundring-frontend:${TAG}
    container_name: frontend-${TAG}
    networks:
      - caddy
    labels:
      caddy: ${TAG}.dundring.com
      caddy.reverse_proxy: '{{upstreams 80}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

networks:
  caddy:
    external: true
  dundring:
