version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-${TAG}
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: dundring
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-uroot',
          '-p${DB_ROOT_PASSWORD}',
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - dundring

  backend:
    image: sivertschou/dundring-backend:${TAG}
    container_name: backend-${TAG}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/dundring
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - caddy
      - dundring
    labels:
      caddy: ${TAG}.dundring.com
      caddy.reverse_proxy: '/api* {{upstreams 8080}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

  frontend:
    image: sivertschou/dundring-frontend:${TAG}
    container_name: frontend-${TAG}
    networks:
      - caddy
    labels:
      caddy: ${TAG}.dundring.com
      caddy.reverse_proxy: '{{upstreams 80}}'
      caddy.tls.dns: 'cloudflare ${CLOUDFLARE_DNS_API_TOKEN}'

networks:
  caddy:
    external: true
  dundring:
