name: Build and deploy

on:
  push:
    branches: [main]

env:
  tag: dev

jobs:
  build:
    name: Build, tag and push image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag and push backend
        uses: docker/build-push-action@v5
        with:
          file: ./apps/backend/Dockerfile
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dundring-backend:${{ steps.gitversion.outputs.semVer }}
          push: true

      - name: Build, tag and push frontend
        uses: docker/build-push-action@v5
        with:
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dundring-frontend:${{ steps.gitversion.outputs.semVer }}

      - name: Set version tag
        run: |
          git tag ${{ steps.gitversion.outputs.semVer }}
          git push origin ${{ steps.gitversion.outputs.semVer }}

  deploy-dev:
    name: Deploy dev
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    using: ./github/workflows/deploy.yaml

  deploy-prod:
    name: Deploy prod
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    using: ./github/workflows/deploy.yaml
