name: Build and deploy preview

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag and push backend
        uses: docker/build-push-action@v5
        with:
          file: ./apps/backend/Dockerfile
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dundring-backend:preview-${{ github.event.number }}
          push: true

      - name: Build, tag and push frontend
        env:
          PR_NUMBER: ${{ github.event.number }}
        uses: docker/build-push-action@v5
        with:
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dundring-frontend:preview-${{ github.event.number }}

      - name: Start frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
            docker stop $(docker container ls -q -f ancestor=${{ vars.DOCKERHUB_USERNAME }}/dundring-frontend:preview-${{ github.event.number }}) || echo "No frontend container to stop"
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/dundring-frontend:preview-${{ github.event.number }}
            docker run -d \
              --network caddy \
              --label caddy=preview-${{ github.event.number }}.dundring.com \
              --label caddy.reverse_proxy="{{upstreams 80}}" \
              --label caddy.tls.dns="cloudflare ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
              ${{ vars.DOCKERHUB_USERNAME }}/dundring-frontend:preview-${{ github.event.number }}

      - name: Start backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
            docker stop $(docker container ls -q -f ancestor=${{ vars.DOCKERHUB_USERNAME }}/dundring-backend:preview-${{ github.event.number }}) || echo "No backend container to stop"
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/dundring-backend:preview-${{ github.event.number }}
            docker run -d \
              --network caddy \
              --label caddy=preview-${{ github.event.number }}.dundring.com \
              --label caddy.reverse_proxy="/api* {{upstreams 8080}}" \
              --label caddy.tls.dns="cloudflare ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
              ${{ vars.DOCKERHUB_USERNAME }}/dundring-backend:preview-${{ github.event.number }}
