name: Lint files

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: '3.0.3'
          dry: True
          prettier_options: --check **/*.{ts,tsx,js,md,html,json} #todo add svg
