name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  YARN_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn
      - run: yarn run build

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: '3.0.3'
          dry: True
          prettier_options: --check **/*.{ts,tsx,js,md,html,json} #todo add svg
